### ISSUE TITLE
Page uses 100% cpu even when not playing video

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/the-shenango-channel#6]
Mac/Chrome

**Comment by pdille** [comment]
Commit b79a87f725 should address this. It isn't the new callback approach we had discussed though. Since that 100ms timer itself wasn't correctly being used, I wanted to fix that first, as it had been copied from Breathe Cam and was being used in that scenario with different assumptions than those being made now in this setup.

Anyway, it should no longer eat CPU when nothing is happening and should greatly alleviate the grapher stuttering we saw.
