### ISSUE TITLE
Time seek inaccurate when zoomed out on timeline and clicking on smell report

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/the-shenango-channel#8]
When I zoom out to show all of March and click on smell reports, sometimes the time is wrong:

![image](https://cloud.githubusercontent.com/assets/324851/7231411/28264312-e743-11e4-92bc-b646a655878e.png)

When I clicked same report again, I got the right time and the report displayed:
![image](https://cloud.githubusercontent.com/assets/324851/7231435/3f7c5e98-e743-11e4-82b1-7d73c23b9d8e.png)

Interestingly, this particular example has two reports within minutes of each other.  Zooming in a bit:
![image](https://cloud.githubusercontent.com/assets/324851/7231482/782f9d2c-e743-11e4-90c5-6330b85a042d.png)

So maybe if the click intersects with multiple smells, maybe there's a race condition as more than one gets seeked to, leaving the possibility of panning to the location from one report and selecting time from another report?

It would be nice to select the one that is currently highlighting on the timeline.

**Comment by pdille** [comment]
This looks like a grapher related problem. Because I am using 5 different channels for the smell reports, the grapher tries to be 'helpful' and displays all the points you are hovering over. You see the same thing if the grapher had two graphs intersecting there -- it would display both values on top of each other.

If you look, you'll see all the comments stacked on each other -- it's much more obvious if the points underneath actually have longer comments. And it appears that when you click a point which may have overlap, then the grapher triggers the click event for every point in that overlap.

So, it isn't actually moving the map and changing the time line to two different things, but rather choosing one of the points in the overlap and going to it. It may look like you are hovering over the top one, because the comment is written on top, but in fact it's more likely highlighting one slightly under. It's really annoying actually.

I have some ideas to work around this, but not seem very clean to me at the moment.

**Comment by rsargent** [comment]
I think it's actually going to multiple, with race condition, because it's
going to the time from one and the location for another.  And sometimes I
see it jog back and forth rapidly.

If so, maybe (ugly) set a timer on that event handler and go with whichever
one was on top according to the order you put them?  (which I think means
go to the stinkiest)

**Comment by rsargent** [comment]
fixed!
